apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nginx-web-fe
  name: nginx-web-fe
  namespace: network
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-web-fe
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx-web-fe
    spec:
      containers:
      - image: nginx:1.20.2
        name: nginx
        resources: {}
status: {}
