apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod100
  name: pod100
spec:
  containers:
  - args:
    - /bin/sh
    - -c
    - echo hello;sleep 30;echo bye
    image: nginx
    name: pod100
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
