pipeline {

  agent any

  stages {

    stage('Checkout Source') {
      steps {
        git url:'https://github.com/alian2000/code.git', branch:'master'
        
      }
    }
    
    def remote = [:]
remote.name = "node"
remote.host = "192.168.86.247"
remote.allowAnyHosts = true

node {
    withCredentials([usernamePassword(credentialsId: 'sshUserAcct', passwordVariable: 'password', usernameVariable: 'userName')]) {
        remote.user = sam
        remote.password = @lquds2008

        stage("SSH Steps Rocks!") {
            writeFile file: 'test.sh', text: 'ls'
            sshCommand remote: remote, command: 'for i in {1..5}; do echo -n \"Loop \$i \"; date ; sleep 1; done'
            sshScript remote: remote, script: 'test.sh'
            sshPut remote: remote, from: 'test.sh', into: '.'
            sshGet remote: remote, from: 'test.sh', into: 'test_new.sh', override: true
            sshRemove remote: remote, path: 'test.sh'
        }
    }
}
    
    
    
    
    
    
    
    
    
    
    
    stage('List pods') {
      steps {    
    withKubeConfig([credentialsId: 'mykubeconfig']) {
        sh 'curl -LO "https://storage.googleapis.com/kubernetes-release/release/v1.20.5/bin/linux/amd64/kubectl"'  
        sh 'chmod u+x ./kubectl'  
        sh './kubectl cp -n jenkins jenkins-794699f9bc-str6n:/tmp/backup/BACKUPSET*.zip /home/sam/jenkins-bkp/.'
        echo "Running ${env.BUILD_ID} on ${env.JENKINS_URL}"
            }
    }

  }
  }
}
