apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: aem-proxy
  name: aem-proxy
  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aem-proxy
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: aem-proxy
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
status: {}
