apiVersion: apps/v4
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: sam-proxy
  name: sam-api
  namespace: dev123
spec:
  replicas: 999
  selector:
    matchLabels:
      app: sam-proxy
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: sam-proxy
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
status: {}
